### ISSUE TITLE
Speaker page is adding an 's' to the beginning of the URL

### ISSUE THREAD

**Issue by ghost** [SeattleCodeCamp/WebSite#52]
the speaker page is adding a ’s’ to the beginning of the URL on the speaker page.

When you click on them you get 404.

You need to check all the external links, 's' is being added to many of them.

Start with speaker, "Karl Shifflett" for bug verification purposes.

**Comment by cfranciscodev** [comment]
Pushed a fix for this one too (not referenced in  the commit because I hadn't seen this issue yet)
