### ISSUE TITLE
Tiles should be fully clickable

### ISSUE THREAD

**Issue by Matthewsre** [SeattleCodeCamp/WebSite#9]
Not just the image and link, entire div should be cliackable

**Comment by cmichaelhansen** [comment]
I've got this one pretty much fixed up and ready to go. Not sure why there is a condition on the double metro tile to check against the name of the tile being "Sponsors" and not building the link yet. I'm assuming it's to kind of turn it off until there is at least one sponsor? 

If you let me know how you want it to work I can make the adjustment and submit a pull request.

**Comment by slobo80** [comment]
If you look at the live site http://seattle.codecamp.us you will notice that the sponsors tile currently has no sponsors. 
The behaviour should be the same regardless of any sponsors being present. If there are no sponsors, we should take the users to sponsors page and display text with url to the contributor information pdf. Actually, we should have this info regardless whether there are any sponsors or not.

**Comment by cmichaelhansen** [comment]
Ok, that's kind of what I was thinking but I wanted to be sure before I made any kind of official change. I've cleaned up the two partials and I'll test my changes a bit before making a pull request.
